export const ActionType = {
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  CLEAR_ALL:'CLEAR_ALL',
  FILTER_TODO: 'FILTER_TODO'
}

export const FilterType = {
  FILTER_ALL: 'FILTER_ALL',
  FILTER_COMPLETED: 'FILTER_COMPLETED',
  FILTER_UNDONE: 'FILTER_UNDONE'
}
